dental-sync/dental-sync

- core/src/main/java/com/senac/dentalsync/core/controller/ProteticoController.java
- core/src/main/java/com/senac/dentalsync/core/persistency/model/BaseEntity.java
- core/src/main/java/com/senac/dentalsync/core/persistency/model/Clinica.java
- core/src/main/java/com/senac/dentalsync/core/persistency/model/Dentista.java
- core/src/main/java/com/senac/dentalsync/core/persistency/model/Paciente.java
- core/src/main/java/com/senac/dentalsync/core/persistency/model/Protetico.java
- core/src/main/java/com/senac/dentalsync/core/persistency/model/Usuario.java
- core/src/main/java/com/senac/dentalsync/core/persistency/repository/ProteticoRepository.java
- core/src/main/java/com/senac/dentalsync/core/service/ProteticoService.java
- front/package-lock.json
…positórios relacionados para herdar corretamete o BaseEntity.
> Issue_0013

- core/src/main/java/com/senac/dentalsync/core/persistency/model/Paciente.java
> fix: ajustado regex do campo nome

- front/src/components/PacienteTable/PacienteTable.css
- front/src/components/PacienteTable/PacienteTable.jsx
padronizando estilo da tabela.
> style: Ajustado a tabela PACIENTE, padronizar cor e estilo

- core/src/main/java/com/senac/dentalsync/core/controller/PacienteController.java
- core/src/main/java/com/senac/dentalsync/core/service/PacienteService.java
exception tirada do controller e adiciona o size para o tamanho de email e telefone.
> feat: adicionar validação com @Size e remover exceções do controller

- front/src/components/PacienteTable/PacienteActionMenu.jsx
- front/src/components/PacienteTable/PacienteTable.jsx
- front/src/pages/Paciente/CadastroPaciente.jsx
- front/src/pages/Paciente/EditarPaciente.css
- front/src/pages/Paciente/EditarPaciente.jsx
- front/src/pages/Paciente/HistoricoPaciente.jsx
- front/src/pages/Paciente/PacientePage.jsx
Ajuste na data, toast e adicionar funcionalidade de não permitir numero no nome
> fix: ajuste na data, arrumar o toast e impedir de digitar numero no nome

- core/src/main/java/com/senac/dentalsync/core/controller/PacienteController.java
- core/src/main/java/com/senac/dentalsync/core/persistency/model/Paciente.java
- front/src/components/PacienteTable/PacienteActionMenu.jsx
- front/src/components/PacienteTable/PacienteTable.jsx
- front/src/pages/Paciente/CadastroPaciente.jsx
- front/src/pages/Paciente/EditarPaciente.jsx
- front/src/pages/Paciente/PacientePage.jsx
Paciente com validações no controler e model ajustado
> Issue 0024

- front/src/components/PacienteTable/PacienteActionMenu.jsx
- front/src/components/PacienteTable/PacienteTable.jsx
- front/src/pages/Paciente/EditarPaciente.jsx
- front/src/pages/Paciente/PacientePage.jsx
FIX: ajusde de bug quando era criado e editado, pois quando executava uma das duas ações, chamava duas vezes o toastify nas paginas quando estava dando sucesso.
> Issue 0025 [fix: ajuste de bug de toastify, chamando duas vezes no useEffect]

- front/src/components/PacienteTable/PacienteTable.jsx
- front/src/pages/Paciente/CadastroPaciente.jsx
- front/src/pages/Paciente/EditarPaciente.jsx
Criado o placeholder para o Paciente padronizando.
> feat: criado o placeholder para os campos de paciente/cadastrar

- front/src/components/Sidebar/NavItem.css
- front/src/components/Sidebar/Sidebar.jsx
> style: adicionado hover na sidebar e destaque na tela atual

- front/src/components/PacienteTable/PacienteTable.css
- front/src/components/PacienteTable/PacienteTable.jsx
- front/src/pages/Paciente/CadastroPaciente.css
- front/src/pages/Paciente/CadastroPaciente.jsx
- front/src/pages/Paciente/EditarPaciente.css
- front/src/pages/Paciente/EditarPaciente.jsx
- front/src/pages/Paciente/HistoricoPaciente.css
- front/src/pages/Paciente/HistoricoPaciente.jsx
Ajustado o Label para identificar como campo obrigatorio, cores de fundo mudadas e padronizado os cards de editar e cadastrar.
> style: Padronizado o card de cadastrar, fundo e campo obrigatorio.

- front/src/pages/Paciente/CadastroPaciente.css
- front/src/pages/Paciente/CadastroPaciente.jsx
- front/src/pages/Paciente/EditarPaciente.jsx
Inserindo tamanho nos INPUT em cadastrar e editar paciente, limite de 255 caracteres.
> feat: aumentado o caracteres para 255 [editar/cadastrar paciente]

- front/src/components/PacienteTable/PacienteTable.css
- front/src/components/PacienteTable/PacienteTable.jsx
- front/src/pages/Paciente/PacientePage.jsx
Criado a ordenação na tabela nos campos ID, nome e status. Usando o mesmo estilo do Dentista.
> feat: criado a ordenação por status, id e nome[PACIENTE]

- front/src/components/PacienteTable/PacienteTable.css
Icone ficou perto do Label dos status e regex criado para aceitar uma letra
> style: ajustado o icone de ordenação e regex

- core/src/main/java/com/senac/dentalsync/core/persistency/model/Paciente.java
> merge issue_0038/development "fix: ajuste no regex campo nome"

- core/src/main/java/com/senac/dentalsync/core/persistency/model/Dentista.java
- core/src/main/java/com/senac/dentalsync/core/persistency/model/Paciente.java
fix: arrumado o campo nome, o campo tinha sido deletado
> merge issue_0044 para development "fix: recolocado o campo nome, tinha sido deletado"

- core/src/main/java/com/senac/dentalsync/core/persistency/model/Paciente.java
- front/src/pages/Paciente/CadastroPaciente.jsx
fix: Ajuste nas validações do formulario na criação de paciente.
> Merge 'issue_0044' into 'development':  fix: ajuste na validação de cadastro Paciente

- core/src/main/java/com/senac/dentalsync/core/controller/PedidoController.java
- core/src/main/java/com/senac/dentalsync/core/dto/AtualizarStatusPedidoDTO.java
- core/src/main/java/com/senac/dentalsync/core/persistency/model/Pedido.java
- core/src/main/java/com/senac/dentalsync/core/persistency/model/Servico.java
- core/src/main/java/com/senac/dentalsync/core/service/PedidoService.java
- front/src/App.jsx
- front/src/components/PedidoForm/PedidoForm.jsx
- front/src/components/PedidoTable/PedidoTable.css
- front/src/components/PedidoTable/PedidoTable.jsx
- front/src/components/SearchBar/SearchBar.css
- front/src/pages/Kanban/Kanban.css
- front/src/pages/Kanban/Kanban.jsx
- front/src/pages/Pedido/PedidoPage.jsx
Criação de toda a tela do Kanban
> Issue 0056

- core/package-lock.json
- core/src/main/java/com/senac/dentalsync/core/controller/RelatorioController.java
- core/src/main/java/com/senac/dentalsync/core/dto/DadosAnterioresDTO.java
- core/src/main/java/com/senac/dentalsync/core/dto/PedidosPorMesDTO.java
- core/src/main/java/com/senac/dentalsync/core/dto/PedidosPorTipoDTO.java
- core/src/main/java/com/senac/dentalsync/core/dto/PedidosRecentesDTO.java
- core/src/main/java/com/senac/dentalsync/core/dto/RelatorioDTO.java
- core/src/main/java/com/senac/dentalsync/core/dto/StatusPedidosDTO.java
- core/src/main/java/com/senac/dentalsync/core/persistency/repository/DentistaRepository.java
- core/src/main/java/com/senac/dentalsync/core/persistency/repository/PedidoRepository.java
- core/src/main/java/com/senac/dentalsync/core/service/RelatorioService.java
- front/src/components/HorizontalBarChart/index.jsx
- front/src/pages/Relatorios/index.jsx
Correção para buscar por ENUM e não STRING. 
Alterado as cores do relatorio e adicionado a formatação dos numeros mostrado.
> [issue_0059] Merge das alterações para development

- front/src/pages/Dentista/DentistaPage.jsx
- front/src/pages/Dentista/EditarDentista.jsx
- front/src/pages/Kanban/Kanban.css
- front/src/pages/Kanban/Kanban.jsx
- front/src/pages/Paciente/CadastroPaciente.jsx
- front/src/pages/Paciente/PacientePage.jsx
- front/src/pages/Protetico/ProteticoPage.jsx
> Issue 0062

- core/src/main/java/com/senac/dentalsync/core/persistency/model/Servico.java
- front/src/components/ActionMenu/ActionMenu.jsx
- front/src/components/ActionMenuClinica/ActionMenuClinica.jsx
- front/src/components/ActionMenuDentista/ActionMenuDentista.jsx
- front/src/components/ClinicaTable/ExpandableClinicaTable.css
- front/src/components/ClinicaTable/ExpandableClinicaTable.jsx
- front/src/components/GenericTable/GenericTable.css
- front/src/components/GenericTable/GenericTable.jsx
- front/src/components/Modals/ModalCadastroCategoriaServico.css
- front/src/components/Modals/ModalCadastroCategoriaServico.jsx
- front/src/components/PacienteTable/PacienteActionMenu.jsx
- front/src/components/ProteticoTable/ProteticoTable.jsx
- front/src/components/ServicoTable/ServicoTable.jsx
- front/src/hooks/useExportCsv.js
- front/src/pages/Kanban/Kanban.jsx
- front/src/pages/Material/MaterialPage.jsx
- front/src/pages/Servico/CadastroServico.css
- front/src/pages/Servico/CadastroServico.jsx
- front/src/pages/Servico/EditarServico.jsx
- front/src/pages/Servico/ServicoPage.jsx
Varias alterações e padronizações no CRUD do Serviço
> Issue 0067

- core/src/main/java/com/senac/dentalsync/core/persistency/repository/DentistaRepository.java
- core/src/main/java/com/senac/dentalsync/core/persistency/repository/PedidoRepository.java
- core/src/main/java/com/senac/dentalsync/core/service/RelatorioService.java
- front/package-lock.json
- front/package.json
- front/src/components/BarChart/index.jsx
- front/src/components/BarChart/styles.css
- front/src/components/HorizontalBarChart/index.jsx
- front/src/components/HorizontalBarChart/styles.css
- front/src/components/RecentOrdersList/index.jsx
- front/src/components/RecentOrdersList/styles.css
- front/src/components/StatCard/index.jsx
- front/src/components/StatCard/styles.css
- front/src/pages/Relatorios/index.jsx
- front/src/pages/Relatorios/styles.css
Retirado o botão impressora da tela de relatorio, adicionado mascara para nomes maiores de 45 caracteres, em pedidos recentes as cores do status no mesmo padrão (amarelo, verde e azul) e agora o sistema baixa um pdf com o print da tela
> Integrando os dados da ISSUE_0068 para Development

- front/src/components/BarChart/index.jsx
- front/src/pages/Paciente/CadastroPaciente.jsx
- front/src/pages/Pedido/PedidoPage.jsx
- front/src/pages/Relatorios/index.jsx
Adicionado uma função para forçar a atualização do grafico.
> Alteração da issue_0068 para development

- core/pom.xml
- core/src/main/java/com/senac/dentalsync/core/persistency/model/EnderecoLaboratorio.java
- core/src/main/java/com/senac/dentalsync/core/persistency/model/Laboratorio.java
- core/src/main/java/com/senac/dentalsync/core/persistency/model/Pedido.java
- core/src/test/java/com/senac/dentalsync/core/model/ClinicaTest.java
- core/src/test/java/com/senac/dentalsync/core/model/DentistaTest.java
- core/src/test/java/com/senac/dentalsync/core/model/EnderecoLaboratorioTest.java
- core/src/test/java/com/senac/dentalsync/core/model/LaboratorioTest.java
- core/src/test/java/com/senac/dentalsync/core/model/MaterialTest.java
- core/src/test/java/com/senac/dentalsync/core/model/PacienteTest.java
- core/src/test/java/com/senac/dentalsync/core/model/PedidoTest.java
- core/src/test/java/com/senac/dentalsync/core/model/ProteticoTest.java
- core/src/test/java/com/senac/dentalsync/core/model/ServicoTest.java
- front/src/pages/Relatorios/index.jsx
Adicionado algumas validações na entidade de Pedido, Laboratori e EnderecoLaboratorio. Criado seus respectivos teste unitario de cada classe e suas validações.
> Alteração da issue_0068 para development feat: adicionado validação na entidade Laboratorio, Pedido e EnderecoLaboratorio e seus teste de entidade

- core/pom.xml
- core/src/test/java/com/senac/dentalsync/core/repository/PacienteRepositoryTest.java
- core/src/test/java/com/senac/dentalsync/core/service/CategoriaMaterialServiceTest.java
- core/src/test/java/com/senac/dentalsync/core/service/CategoriaServicoServiceTest.java
- core/src/test/java/com/senac/dentalsync/core/service/ClinicaServiceTest.java
- core/src/test/java/com/senac/dentalsync/core/service/DentistaServiceTest.java
- core/src/test/java/com/senac/dentalsync/core/service/MaterialServiceTest.java
- core/src/test/java/com/senac/dentalsync/core/service/PacienteServiceTest.java
Adicionando teste para entidade e service. Cobrindo 100% de acordo com JaCoCo.
> Alteração da issue_0068 para development feat: Adicionando teste para entidade e service. Cobrindo 100% de acordo com JaCoCo. 

- core/pom.xml
- core/src/main/java/com/senac/dentalsync/core/controller/UsuarioController.java
- core/src/main/java/com/senac/dentalsync/core/util/CNPJValidator.java
- core/src/test/java/com/senac/dentalsync/core/controller/AuthControllerTest.java
- core/src/test/java/com/senac/dentalsync/core/controller/CategoriaMaterialControllerTest.java
- core/src/test/java/com/senac/dentalsync/core/controller/CategoriaServicoControllerTest.java
- core/src/test/java/com/senac/dentalsync/core/controller/ClinicaControllerTest.java
- core/src/test/java/com/senac/dentalsync/core/controller/DentistaControllerTest.java
- core/src/test/java/com/senac/dentalsync/core/controller/LaboratorioControllerTest.java
- core/src/test/java/com/senac/dentalsync/core/controller/MaterialControllerTest.java
- core/src/test/java/com/senac/dentalsync/core/controller/PacienteControllerTest.java
- core/src/test/java/com/senac/dentalsync/core/controller/PedidoControllerTest.java
- core/src/test/java/com/senac/dentalsync/core/controller/ProteticoControllerTest.java
- core/src/test/java/com/senac/dentalsync/core/controller/RelatorioControllerTest.java
- core/src/test/java/com/senac/dentalsync/core/controller/SecurityControllerTest.java
- core/src/test/java/com/senac/dentalsync/core/controller/ServicoControllerTest.java
- core/src/test/java/com/senac/dentalsync/core/controller/UsuarioControllerTest.java
- core/src/test/java/com/senac/dentalsync/core/service/EmailServiceTest.java
- core/src/test/java/com/senac/dentalsync/core/service/LaboratorioServiceTest.java
- core/src/test/java/com/senac/dentalsync/core/service/PacienteServiceTest.java
- core/src/test/java/com/senac/dentalsync/core/service/PedidoServiceTest.java
- core/src/test/java/com/senac/dentalsync/core/service/ProteticoServiceTest.java
- core/src/test/java/com/senac/dentalsync/core/service/RelatorioServiceTest.java
- core/src/test/java/com/senac/dentalsync/core/service/RememberMeServiceTest.java
- core/src/test/java/com/senac/dentalsync/core/service/ServicoServiceTest.java
- core/src/test/java/com/senac/dentalsync/core/service/TrustedDeviceServiceTest.java
- core/src/test/java/com/senac/dentalsync/core/service/TwoFactorServiceTest.java
- core/src/test/java/com/senac/dentalsync/core/service/UsuarioServiceTest.java
- core/src/test/java/com/senac/dentalsync/core/util/CNPJValidatorTest.java
- core/src/test/java/com/senac/dentalsync/core/util/ServicoCalculatorUtilTest.java
feat: adicionado todos os testes para development. Usei JaCoCo para validar os testes necessarios para o sistema, apontou 76%.
> Alteração da issue_0069 para development feat: adicionado todos os testes e cobrindo 70% 
